sudo: required

language: java

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  # Update
  - sudo apt-get update

  # Change the system docker-compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Upgrade Docker
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker-compose up