version: '3'

services:

  tesseract4:

    build: ./

    image: tesseract4:latest

    container_name: tesseract4-container

    ports:
       - '4022:22'

    volumes:
        - /Users/ivantha:/Users/ivantha

    command: >
        bash -c "./docker-scripts/1-update-src.sh
        && ./docker-scripts/2-compile-src.sh"
